#!/bin/bash

process="$(ps -aux | awk '{print $2,$11}' | grep puma | wc -l)"
pid="$(ps -aux | awk '{print $2","$11}' | grep puma | awk -F',' '{print $1}')"

NAGIOS=('0' '1' '2' '3');

if [ "$process" -ne 1 ] || [ "$process" -eq 0 ]
then
	#echo "Oxidized Not Running"
	for i in $pid
	do
		kill -9 $i
	done
	#echo "Starting Oxidized"
	su - oxidized -c "oxidized &"
	if [ $? -eq 0 ]
	then
		#echo "Oxidized Started"
		exit ${NAGIOS[0]}
	else
		#echo "Oxidized Failed To Start"
		exit ${NAGIOS[2]}
	fi
else
	#echo "Oxidized is Running on port $pid"
	exit ${NAGIOS[0]}
fi
